# Generated by Django 3.1.7 on 2021-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('Class', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
